# Generated by Django 5.1.4 on 2025-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('anons', models.CharField(max_length=250, null=True, verbose_name='Anons')),
                ('full_text', models.TextField(null=True, verbose_name='Article')),
                ('date', models.DateTimeField(null=True, verbose_name='Data of publishment')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
