# Generated by Django 5.1.4 on 2025-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='full_text',
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
